name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permission for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# One deploy at the time
concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    name: Compiling CookBook
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependency
        run: npm ci

      - name: Build with Astro
        run: npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Publish on GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
